name: gaap
description: Roll Strategic Situation Panel(App difference & team member difference - between you and me)

version: 1.0.1+117

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.2.0+1

  cupertino_icons: ^0.1.2
  flutter_sparkline: "^0.1.0"
  # flutter_staggered_grid_view: "^0.3.0"
  # flutter_circular_chart: ^0.1.0
  # font_awesome_flutter: ^8.2.0
  http: ^0.12.1
  bubble: ^1.1.9+1
  grouped_list: ^2.0.0
  date_format: ^1.0.8
  intl: ^0.16.1
  #transparent_image: ^1.0.0
  #grouped_checkbox: ^1.0.0
  #responsive_widgets: ^2.0.1
  #json_annotation: ^2.0.0
  path_provider: ^1.4.0
  draggable_scrollbar: ^0.0.4
  provider: ^4.1.3
  #photo_view: ^0.9.2
  #shared_preferences: ^0.5.7+1
  google_sign_in: ^4.5.1          # Google oAuth
  firebase_dynamic_links: ^0.3.0

  cloud_firestore: ^0.13.7        # 새로운 Flutter 앱 생성 및 의존성 업데이트
  firebase_core: ^0.4.5           # This dependency was added during initial configuration.
  firebase_analytics: ^5.0.15     # add dependency for Google Analytics for Firebase
  firebase_auth: ^0.16.0

  # apple_sign_in: ^0.1.0
  sign_in_with_apple: ^2.5.1

  logger: ^0.9.1
  flutter_tags: ^0.4.8+1
  image_picker: ^0.6.7+4
  network_to_file_image: ^2.3.1
  flutter_swiper: ^1.1.6
  extended_image: ^0.8.0
  image: ^2.1.12
  draggable_scrollbar_sliver: ^0.0.3
  webview_flutter: ^0.3.19+9
  linked_scroll_controller: ^0.1.2

  firebase_admob: ^0.9.3+2
  admob_flutter: ^0.3.4
  flutter_native_admob: ^2.1.0

  fluttericon: ^1.0.7
  liquid_progress_indicator: ^0.3.2
  page_transition: ^1.1.5
  pull_to_refresh: ^1.1.6
  dio: ^3.0.9
  flutter_statusbarcolor: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/gaap_logo.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"
  # PNG 변경 후 실행 명령어
  # flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  fill: true
  image: assets/splash/gaap_Splash_S.png
  color: "#020659"
  android_disable_fullscreen: true
   # PNG 변경 후 실행 명령어
  # flutter pub pub run flutter_native_splash:create

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data_repo/
    - lib/
    - images/
    - images/api_source/
    - images/api_source/champion_square/
    - images/api_source/passive/
    - images/api_source/qwer/
    - images/api_source/emblems/
    - images/api_source/ranked-positions/
    - images/chat/
    - images/chat/avatar/
    - images/chat/emoji/
    - images/etc/